---
- name: Download ngrok
  get_url: url=https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip dest=/home/vagrant/ngrok.zip mode=0775

- name: Unarchive ngrok
  sudo: yes
  shell: unzip -o /home/vagrant/ngrok.zip -d /usr/local/bin/
  when: inventory_hostname == "192.168.56.128"

- name: Copy ngrok
  sudo: yes
  shell: chmod 0755 /usr/local/bin/ngrok
  when: inventory_hostname == "192.168.56.128"

- name: Install jq
  sudo: yes
  shell: curl http://stedolan.github.io/jq/download/linux64/jq > /usr/local/bin/jq && chmod 0755 /usr/local/bin/jq

- name: Start
  sudo: yes
  shell: nohup /usr/local/bin/ngrok http 80 > /var/log/ngrok.log 2>&1 &
  when: inventory_hostname == "192.168.56.128"

- name: Output ngrok tunnel
  sudo: yes
  shell: sleep 4 && curl -s http://127.0.0.1:4040/api/tunnels | jq '. | .tunnels[0].public_url' > /home/vagrant/ngrok.tunnel && cat /home/vagrant/ngrok.tunnel
  when: inventory_hostname == "192.168.56.128"
