# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "imagick"

    twig:
        mode: lazy

    filter_sets:
        cache: ~
        entry_thumbnail:
            filters:
                auto_rotate: ~
                relative_resize:
                    heighten: 800
            post_processors:
                jpegoptim: { strip_all: true, max: '%jpeg_quality%', progressive: true }
                optipng: { strip_all: true, level: '%png_level%' }
        low_entry_thumbnail:
            filters:
                auto_rotate: ~
                relative_resize:
                    heighten: 500
                blur: { sigma: 4 }
            post_processors:
                jpegoptim: { strip_all: true, max: 25, progressive: true }
                optipng: { strip_all: true, level: '%png_level%' }
        entry_show:
            filters:
                auto_rotate: ~
                relative_resize:
                    widen: 1920
            post_processors:
                jpegoptim: { strip_all: true, max: '%jpeg_quality%', progressive: true }
                optipng: { strip_all: true, level: '%png_level%' }
        tour_thumbnail:
            filters:
                auto_rotate: ~
                thumbnail:
                    size: [1080, 500]
                    mode: outbound
            post_processors:
                jpegoptim: { strip_all: true, max: '%jpeg_quality%', progressive: true }
                optipng: { strip_all: true, level: '%png_level%' }
