twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - 'templates/form/theme.html.twig'
    globals:
        locales: '%app.locales%'
        matomo_host: '%env(string:MATOMO_HOST)%'
        matomo_site_id: '%env(string:MATOMO_SITE_ID)%'
        thunderforest_tiles_api_key: '%env(string:THUNDERFOREST_TILES_API_KEY)%'

when@test:
    twig:
        strict_variables: true
