twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - 'templates/form/theme.html.twig'
    globals:
        locales: '%app.locales%'
        ga: '%env(string:GOOGLE_ANALYTICS)%'

when@test:
    twig:
        strict_variables: true
