build:
    nodes:
        analysis:
            project_setup:
                override:
                    - 'true'
            tests:
                override:
                    - ./vendor/bin/simple-phpunit
                    - php-scrutinizer-run
                    - js-scrutinizer-run

    dependencies:
        before:
            - mysql -uroot -e 'CREATE DATABASE application_test'
        override:
            - composer install --no-interaction
            - php bin/console doctrine:schema:update --force --env=test
            - php bin/console doctrine:fixtures:load --no-interaction --env=test
            - npm install
            - npm run build

    environment:
        timezone: Europe/Berlin
        apt_packages:
            - libmagickwand-dev
            - libmagickcore-dev
        php:
            version: "8.1"
            pecl_extensions:
                - apcu
                - imagick
        python:
            version: "3.6.0"
            virtualenv: true
        node: "v16.17.1"
        postgresql: false
        rabbitmq: false
        redis: false

    services:
        mariadb: 10

filter:
    excluded_paths:
        - '.github/*'
        - 'tests/*'
        - 'bin/*'
        - 'var/*'
        - 'public/assets/*'

checks:
    php: true
    javascript: true
