build:
    nodes:
        analysis:
            project_setup:
                override:
                    - 'true'
            tests:
                override:
                    - php-scrutinizer-run
                    - js-scrutinizer-run

    environment:
        timezone: Europe/Berlin
        apt_packages:
            - libmagickwand-dev
            - libmagickcore-dev
        php:
            version: "8.1"
            pecl_extensions:
                - apcu
                - imagick
        python:
            version: "3.6.0"
            virtualenv: true
        node: "v16.17.1"
        postgresql: false
        rabbitmq: false
        redis: false

filter:
    excluded_paths:
        - '.github/*'
        - 'tests/*'
        - 'bin/*'
        - 'var/*'
        - 'public/assets/*'

checks:
    php: true
    javascript: true
