build:
    nodes:
        analysis:
            project_setup:
                override:
                    - 'true'
            tests:
                override:
                    - ./vendor/bin/simple-phpunit
                    - php bin/security-checker.phar security:check composer.lock
                    - php-scrutinizer-run
                    -
                        command: phpcs-run
                        use_website_config: true
                    - js-scrutinizer-run

    dependencies:
        before:
            - mysql -uroot -e 'CREATE DATABASE application'
        override:
            - composer install --no-interaction
            - php bin/console doctrine:migrations:migrate --no-interaction
            - php bin/console doctrine:fixtures:load --no-interaction
            - npm install
            - npm run build

    environment:
        timezone: Europe/Berlin
        php:
            version: "7.4"
        postgresql: false
        rabbitmq: false
        mysql: 5.7
        redis: false

filter:
    excluded_paths:
        - '.github/*'
        - 'app/*'
        - 'tests/*'
        - 'bin/*'
        - 'var/*'
        - 'public/assets/*'

checks:
    php: true
    javascript: true
