<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Tag;

/**
 * EntryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntryRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Find entries by a tag
     *
     * @param Tag $tag
     * @return array
     */
    public function findEntriesByTag(Tag $tag)
    {
        $qb = $this->createQueryBuilder("e")
            ->where(':tag MEMBER OF e.file')
            ->setParameters(array('tag' => $tag));
        return $qb->getQuery()->getResult();
    }
}
