<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Entry;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Find tags by a entry
     *
     * @param Entry $entry
     * @return array
     */
    public function findTagsByEntry(Entry $entry)
    {
        $qb = $this->createQueryBuilder("t")
            ->where(':entry MEMBER OF t.entry')
            ->setParameters(array('entry' => $entry));
        return $qb->getQuery()->getResult();
    }
}
