<?php

namespace AppBundle\Repository;

/**
 * TourRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TourRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Return query to load all entries.
     *
     * @return \Doctrine\ORM\Query The query
     */
    public function getFindAllQuery()
    {
        $query = $this->createQueryBuilder('t')
            ->select('t')
            ->orderBy('t.updated', 'DESC')
            ->getQuery();

        return $query;
    }

    /**
     * Find a tag by criteria
     * Need this special function, because of translatable
     * https://github.com/stof/StofDoctrineExtensionsBundle/issues/232.
     *
     * @param $params
     *
     * @return mixed
     */
    public function findOneByCriteria(array $params)
    {
        $query = $this->createQueryBuilder('t');

        foreach ($params as $column => $value) {
            $query->andWhere("t.$column = :$column")
                ->setParameter($column, $value);
        }

        $query = $query->getQuery();

        $query->setHint(\Doctrine\ORM\Query::HINT_CUSTOM_OUTPUT_WALKER, 'Gedmo\\Translatable\\Query\\TreeWalker\\TranslationWalker');

        return $query->getOneOrNullResult();
    }
}
