---

- name: Add ppa Repository
  sudo: yes
  apt_repository: repo=ppa:ondrej/php

- name: Add multiverse Repositories
  sudo: yes
  apt_repository: repo='deb http://archive.ubuntu.com/ubuntu trusty multiverse' state=present

- name: Add multiverse Repositories
  sudo: yes
  apt_repository: repo='deb http://archive.ubuntu.com/ubuntu trusty-updates multiverse' state=present

- name: Add multiverse Repositories
  sudo: yes
  apt_repository: repo='deb http://security.ubuntu.com/ubuntu trusty-security multiverse' state=present

- name: Update apt
  sudo: yes
  apt: update_cache=yes

- name: Install System Packages
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - curl
    - wget
    - python-software-properties

- name: Install Extra Packages
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - vim
    - git
    - htop
    - imagemagick
    - unzip

- name: Configure the timezone
  sudo: yes
  template: src=timezone.tpl dest=/etc/timezone

- name: More Configure the timezone
  sudo: yes
  file: src=/usr/share/zoneinfo/{{timezone}} dest=/etc/localtime state=link force=yes backup=yes

- name: Set the hostname in /etc/hostname
  shell: echo {{ hostname }} > /etc/hostname
  when: hostname is defined

- name: Set the hostname
  shell: hostname {{ hostname }}
  when: hostname is defined

- name: Update /etc/hosts
  sudo: yes
  lineinfile: dest=/etc/hosts regexp='^127\.0\.0\.1' line='127.0.0.1 localhost {{ hostname }}' owner=root group=root mode=0644
