<?php

namespace App\Repository;

use App\Entity\Tour;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * TourRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TourRepository extends EntityRepository
{
    /**
     * Return query to load all entries.
     *
     * @return \Doctrine\ORM\Query The query
     */
    public function getFindAllQuery(): Query
    {
        $query = $this->createQueryBuilder('t')
            ->select('t')
            ->orderBy('t.updated', 'DESC')
            ->getQuery();

        return $query;
    }

    /**
     * Get the page for $tour on the tour index page.
     *
     * @param Tour $tour The tour to find the page for
     *
     * @return int The page where $tour is find
     */
    public function findTourListPageNumber(Tour $tour): int
    {
        $tours = $this->getFindAllQuery()->getResult();

        $pos = array_search($tour, $tours);

        return (int) ceil(($pos + 1) / Tour::PAGINATION_QUANTITY);
    }

    /**
     * Find a tag by criteria
     * Need this special function, because of translatable
     * https://github.com/stof/StofDoctrineExtensionsBundle/issues/232.
     *
     * @param $params
     *
     * @return Tour|null
     */
    public function findOneByCriteria(array $params): ?Tour
    {
        $query = $this->createQueryBuilder('t');

        foreach ($params as $column => $value) {
            $query->andWhere("t.$column = :$column")
                ->setParameter($column, $value);
        }

        $query = $query->getQuery();

        $query->setHint(Query::HINT_CUSTOM_OUTPUT_WALKER, 'Gedmo\\Translatable\\Query\\TreeWalker\\TranslationWalker');

        return $query->getOneOrNullResult();
    }
}
