<?php

namespace App\Repository;

use App\Entity\Tour;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Common\Persistence\ManagerRegistry;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;
use Gedmo\Translatable\TranslatableListener;

/**
 * TourRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TourRepository extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $managerRegistry)
    {
        parent::__construct($managerRegistry, Tour::class);
    }

    /**
     * Return query to load all entries.
     */
    public function getFindAllQuery(): Query
    {
        return $this->createQueryBuilder('t')
            ->select('t')
            ->orderBy('t.updated', 'DESC')
            ->getQuery();
    }

    /**
     * Get the page for $tour on the tour index page.
     *
     * @param Tour $tour The tour to find the page for
     *
     * @return int The page where $tour is find
     */
    public function findTourListPageNumber(Tour $tour): int
    {
        $tours = $this->getFindAllQuery()->getResult();

        $pos = array_search($tour, $tours);

        return (int) ceil(($pos + 1) / Tour::PAGINATION_QUANTITY);
    }

    /**
     * Find a tag by criteria
     * Need this special function, because of translatable
     * https://github.com/stof/StofDoctrineExtensionsBundle/issues/232.
     */
    public function findOneByCriteria(string $locale, array $params = []): ?Tour
    {
        $qb = $this->createQueryBuilder('t');

        foreach ($params as $column => $value) {
            $qb->andWhere("t.$column = :$column")
                ->setParameter($column, $value);
        }

        $query = $qb->getQuery();

        $query
            ->setHint(Query::HINT_CUSTOM_OUTPUT_WALKER, 'Gedmo\\Translatable\\Query\\TreeWalker\\TranslationWalker')
            ->setHint(TranslatableListener::HINT_TRANSLATABLE_LOCALE, $locale);

        return $query->getOneOrNullResult();
    }
}
