#index:
#    path: /
#    controller: App\Controller\DefaultController::index

logout:
    path: /logout

imprint-dataprotection:
    path: /{_locale}/privacy
    requirements:
        _locale: "%app.locales%"
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    frontend/static/privacy.html.twig
