homepage:
    path: /{_locale}/
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    requirements:
        _locale: "%app.locales%"
    defaults:
        template: frontend/index.html.twig

imprint-dataprotection:
    path: /{_locale}/privacy
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    requirements:
        _locale: "%app.locales%"
    defaults:
        template: frontend/static/privacy.html.twig

logout:
    path: /logout
