#index:
#    path: /
#    controller: App\Controller\DefaultController::index

logout:
    path: /logout

imprint-dataprotection:
    path: /{_locale}/privacy
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    requirements:
        _locale: "%app.locales%"
    defaults:
        template: frontend/static/privacy.html.twig
