---
# application tasks to be customized and to run after the main provision
- name: Setup watcher nfs cache clearing
  sudo: yes
  shell: watch -n16 "sysctl -w vm.drop_caches=3" > /dev/null &
  when: inventory_hostname == "192.168.56.128"

- name: Create tmpfs
  sudo: yes
  mount: name=/vagrant/app/cache src=none fstype=tmpfs opts="size=256m" state=mounted

- name: Composer install
  sudo: yes
  shell: cd /vagrant && composer install

- cron: name="Clear profiler cache"
        user="root"
        weekday="*"
        minute="5/*"
        hour="*"
        job="cd /vagrant/app/cache/dev/profiler && ls -t | awk 'NR>5' | xargs rm -rf"

- cron: name="Clear profiler cache"
        user="root"
        weekday="*"
        minute="5/*"
        hour="*"
        job="cd /vagrant/app/cache/prod/profiler && ls -t | awk 'NR>5' | xargs rm -rf"
