name: Coding Standards

on:
    push:
        branches:
            - master
    pull_request:

jobs:
    php-cs-fix:
        name: PHP-CS-Fixer
        runs-on: ubuntu-20.04
        if: github.actor != 'dependabot[bot]'
        steps:
            -   name: Checkout code
                uses: actions/checkout@v3
                with:
                    ref: ${{ github.head_ref }}

            -   name: Run PHP-CS-Fixer
                run: bin/php-cs-fixer

            -   name: Commit and push back changes
                uses: stefanzweifel/git-auto-commit-action@v4
                with:
                    commit_message: "Fix CS with PHP-CS-Fixer"

    js-cs-fix:
        name: ESLint
        runs-on: ubuntu-20.04
        steps:
            -   name: Checkout code
                uses: actions/checkout@v3
                with:
                    ref: ${{ github.head_ref }}

            -   name: Install modules
                run: npm install

            -   name: Run ESLint
                run: node_modules/eslint/bin/eslint.js assets/js --fix

            -   name: Commit and push back changes
                uses: stefanzweifel/git-auto-commit-action@v4
                with:
                    commit_message: "Fix CS with ESLint"
